alias Programs="cd /home/daniel75027/Desktop/Programs/"
alias EMULATOR="cd $ANDROID_HOME/tools && emulator -avd Nexus_5X_API_23 -use-system-libs"
alias PCIT="cd /home/daniel75027/Desktop/Programs/PCIT"
alias Transmission_Start="sudo service transmission-daemon start"
alias Transmission_Stop="sudo service transmission-daemon stop"
